### ISSUE TITLE
Zero-width non-joiner cannot be typed/sent

### ISSUE THREAD

**Issue by rayeshman** [QMatrixClient/Quaternion#164]
I chat in Persian and whenever I try to type [this character](https://en.wikipedia.org/wiki/Zero-width_non-joiner) it cannot be typed, I haven't had this problem in any other program.

**Comment by KitsuneRal** [comment]
Good day. What's your operating system and Qt version?

**Comment by rayeshman** [comment]
Ubuntu 16.04, The latest version in repository I guess;

```
qmake --version
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

```
It can be a compile problem though

**Comment by KitsuneRal** [comment]
You can run `apt-cache show qt5-default` for that matter, I believe. If you didn't upgrade your package base from some PPA, you most likely have Qt 5.5.1. Apparently, you have this problem then: https://bugreports.qt.io/browse/QTBUG-42074 . You haven't seen it in other applications, probably, because they are not Qt-based. And, as mentioned in the bug, you should upgrade either to Qt 5.6.3 or all the way to Qt 5.9.0, released a couple of weeks ago, in order to have this fixed.

**Comment by rayeshman** [comment]
> Version: 5.5.1+dfsg-16ubuntu7
Yes, I rarely use Qt-based software and I'm pretty much sure it's the problem reported in Qt bug reports
Thanks.
