### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by baimafeima** [QMatrixClient/Quaternion#180]
It's been over a year since the last tagged release. How far away are you from releasing the next version? Would be great to tag releases in shorter intervals if possible.

**Comment by KitsuneRal** [comment]
Actually, the next release is well on the radar now, even though that is not noted anywhere :) I'd like to make a release of libqmatrixclient first, and a Quaternion release will come shortly afterwards. I guess, by the end of October will be done with both.

I hear you and I'm fully aligned that tag releases should be made a routine rather than an annual celebration. This is also being considered - most likely, we'll adopt a "when it's ready" approach of Debian, when workability of a certain feature-set is a criteria to release the next version. While still depending on availability of developers (i.e., me), this should further happen on a more regular basis, probably once in 1-3 months.

**Comment by KitsuneRal** [comment]
In order to not delay further on the release, there's going to be "alpha"-version 0.0.4, which is essentially whatever Quaternion is now on top of libqmatrixclient v0.1 (actually already quite stable and featureful, especially compared to other desktop clients). This can be used for packaging. The next version (0.0.5) is going to be the first official beta, focused on bugfixing but probably with some more features as well (watch [Projects/Roadmap](https://github.com/QMatrixClient/Quaternion/projects/2) for details).

**Comment by KitsuneRal** [comment]
https://github.com/QMatrixClient/Quaternion/releases/tag/v0.0.4

**Comment by KitsuneRal** [comment]
In the end, 0.0.4 has been dubbed "beta", as it's already capable of enough things to let more people in.
