### ISSUE TITLE
Optionally wrap messages below usernames

### ISSUE THREAD

**Issue by alphapapa** [QMatrixClient/Quaternion#218]
Hi,

It would be nice if the message text could be wrapped below the username in the message list.  As it is, there's a lot of whitespace in the message list because the message text is left-aligned to the right edge of the timestamp-username metadata.  It isn't a big deal when the window is very wide, but when the window is relatively small, it forces the message text into a small area and wastes a lot of screen space.

Thanks for your work on Quaternion!

**Comment by KitsuneRal** [comment]
That's indeed a shortcoming, and I think people were asking about that in #quaternion before. Thanks for documenting it.
To change the layout should be relatively easy change for anybody who speaks QML; making a decent logic that would intelligently kick in wrapping is a bit more complex but most likely can be done within QML too. At least, we can always go with setting up one more UI option, especially because opinions about the layout seem to be rather polarised: some IRC folks tend to strongly prefer tabular layout (because of CLI IRC clients legacy) while general audience likes wrapped layout more, as it's pretty much standard among IM clients these days (and Riot uses it as well).

**Comment by KitsuneRal** [comment]
Quaternion 0.0.9.2 has a new default layout with the message under the username (see https://github.com/QMatrixClient/Quaternion/releases/tag/v0.0.9.2).
