### ISSUE TITLE
Can't connect to riot.im: Not Found error

### ISSUE THREAD

**Issue by shmerl** [QMatrixClient/Quaternion#251]
Is it possible to connect to to riot.im using Quaternion client? I just built it from source, and when connecting to https://riot.im it gives me:

`Error transferring https://riot.im/_matrix/client/r0/login - server replied: Not Found`

**Comment by KitsuneRal** [comment]
As already mentioned in #quaternion, there's confusion between a _Matrix server_ and a _web server for Riot.im, a Matrix client_. Even though you register a Matrix user using Riot.im, you actually register it on a _Matrix server_, which is most likely `matrix.org` in your case. In order to login with Quaternion 0.0.5 you only need to specify your full user id (such as `#username:matrix.org`, and Quaternion will automatically find out which server it should connect to (`https://matrix.org`).

**Comment by KitsuneRal** [comment]
Btw, specifying a local part of user id (plain `username`) and using a default value for "Connect to" input will also work.
