### ISSUE TITLE
Segmentation fault on exiting quaternion

### ISSUE THREAD

**Issue by haadr** [QMatrixClient/Quaternion#376]
### Description

Quaternion segfaults on exit.

### Steps to reproduce

- run quaternion in a terminal
- log in
- exit quaternion via the window manager or via Accounts/Quit
- Notice the segmentation fault in the terminal

### Version information

- Quaternion git commit f647f64
- Qt 5.7.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.3.0 20170124) on "xcb" 

- Quaternion compiled from repo
- OS: Debian GNU/Linux 9 (stretch) [linux version 4.16.0-2-amd64] with some packages from testing

Can provide  qtdiag info if necessary.

# Interesting parts of log

```
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 2
Last window closed!
libqmatrixclient.jobs.sync: "SyncJob-3" stopped without ready network reply
Segmentation fault
```

# gdb backtrace

Attached.
[bt.log](https://github.com/QMatrixClient/Quaternion/files/2160060/bt.log)

**Comment by KitsuneRal** [comment]
For the record, can you please drop the first 10 lines of the logs too? I specifically need a line mentioning that Quaternion uses `QQuickView` rather than `QQuickWidget`.
Unfortunately, judging by the stacktrace, the problem is inside Qt code - specifically, an attempt is made to cleanup the QML engine probably already deleted by then. Upgrading your Qt version may help.
