### ISSUE TITLE
Room Tag added using Quaternion break the account_data inside of the room

### ISSUE THREAD

**Issue by MTRNord** [QMatrixClient/Quaternion#432]
### Description

When adding a Room tag using Quaternion the m.tag event gets broken and that seems to break also some parts of the API.

Result after adding a tag:

```
"account_data": {
          "events": [
            {
              "content": {
                "tags": {
                  "m.favourite": {
                    "order": 0.2817608267132813
                  }
                }
              },
              "type": "m.tag"
            },
            {
              "content": {
                "tags": {
                  "m.favourite": {
                    "order": ""
                  },
                  "Freifunk": {
                    "order": ""
                  }
                }
              },
              "type": "m.tag"
            }
          ]
        },
```

### Steps to reproduce

- Add a Room Tag to a Room

Describe how what happens differs from what you expected: It obviously should never break the events

### Version information

- **Quaternion version**: 0.0.9.2
- **Qt version**: 
- **Install method**: Arch AUR
- **Platform**: Antergos Arch Linux

**Comment by MTRNord** [comment]
The matching issue about the API getting broken by this is: https://github.com/matrix-org/synapse/issues/4053

**Comment by KitsuneRal** [comment]
As discussed in #qmatrixclient: this looks to be a consequence of Quaternion 0.0.9.2 using strings instead of floats for tag order value (driven in turn by https://github.com/matrix-org/matrix-doc/issues/1565) and/or Synapse not overwriting the previous tag value when a tag with the same name gets added (probably triggered by the Quaternion's legacy behaviour). Quaternion master and upcoming Quaternion 0.0.9.3 use floats for tag order type.
You might be able to fix things by using PUT /tags/m.favourite or even by PUTting /account_data/m.tag which will (at least, should) overwrite all tags for the room entirely. The second request is pretty easy to accomplish using Riot's /devtools (just edit the contents of the `m.tag` room account data event).
P.S. Using tags with marginal or incorrect order values (e.g., `0`, `1`, `""` or `null`) produces pretty weird effects in Riot. At the same time I could not reproduce the duplication of tags on my end by whatever means (even through Riot's /devtools). Apparently, Riot is paranoid enough about user input but quite relaxed on what comes from the wire.
