### ISSUE TITLE
Matrix.org : Try Matrix : Quaternion : page not up to date

### ISSUE THREAD

**Issue by almereyda** [QMatrixClient/Quaternion#567]
The page https://matrix.org/docs/projects/client/quaternion.html, which is featured very high on https://matrix.org/docs/projects/try-matrix-now.html, links to [various package repositories](https://repology.org/metapackage/quaternion/information) at `https://repology.org/metapackage/quaternion/information`.

Since https://github.com/QMatrixClient/Quaternion/releases/tag/0.0.9.4-beta2 this should point at https://bintray.com/qmatrixclient/ci/Quaternion#files instead.

**Comment by KitsuneRal** [comment]
Thank for the idea but rather than that I'm pushing to release 0.0.9.4 as soon as possible. I appreciate that CI outputs look suitable for general usage but I'm not quite fond of providing a link to them to wider public. And those ready to tinker with Quaternion more intimately should easily find the link to CI in the project's README.md.
